// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DbgPkgsEnabler
{
    internal sealed partial class Vsix
    {
        public const string Id = "DbgPkgsEnabler.e2c91054-5cb7-4668-b161-02fc5bfb59a4";
        public const string Name = "DbgPkgsEnabler";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Catalin Siicu csiicu";
        public const string Tags = "";
    }
}
